name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

# Give the workflow  permission to deploy the pages inside 
permissions: 
  contents: read
  pages: write
  id-token: write

  # Do not cancel in-progress runs as we want to allow there production deployment to complete

jobs:
  test-api:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shard: [1/2, 2/2]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm install -g pnpm && pnpm install
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
      - name: Run Playwright tests
        run: pnpm exec playwright test --shard ${{matrix.shard}} --grep @api
        env:
          BASE_URL: https://automationintesting.online/
          DEV_EMAIL: devkuku@sample-no.com
          PASSWORD: dev_spearcad
          DEVNAME: "Dev Kuku"
      - uses: actions/upload-artifact@v4
        name: Upload blob report to github actions artifacts
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 14
      # Configure Pages 
      - name: Configure Github Pages
        uses: actions/configure-pages@v4

      # Uplaod the report as a page artifcat 
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
        path: playwright-report/

deploy:
  needs: test
  environment:
    name: github-pages
    url: $${{steps.deployment.outputs.page_url}}
  runs-on: ubuntu-latest
  steps:
  - name: Deploy to Github Pages
    uses: action/deploy-pages@v3

  